require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - db/migrate/*.rb
    - app/views/**/*.slim

Layout/LineLength:
  # Max: 100
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case