default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>_development
  port: <%= ENV.fetch('DB_PORT') { '5432' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  variables:
    statement_timeout: <%= ENV.fetch('PG_STATEMENT_TIMEOUT') { '20000' } %>

development:
  <<: *default

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
